
/**
 * Constants for action types in Reports view.
 */
export const reportsActionTypes = {
    DONWLOAD_SURVEYS_EXCEL:'DONWLOAD_SURVEYS_EXCEL',
    SET_PANEL_EXPAND_REPORTS:'SET_PANEL_EXPAND_REPORTS',
    SET_PANEL_RELOAD_REPORTS_REFRESH:'SET_PANEL_RELOAD_REPORTS_REFRESH',
    SET_PANEL_COLLAPSE_REPORTS:'SET_PANEL_COLLAPSE_REPORTS',
    SET_PANEL_REMOVE_REPORTS:'SET_PANEL_REMOVE_REPORTS'
};